### PR TITLE
Translation of the Server ID

### PR DESCRIPTION
**Pull request by stephdl**

### CODE REVIEW

**Comment by stephdl** [comment]
@gsanchietti don't forget this PR :)

**Comment by gsanchietti** [comment]
Should I get this commit and move it to the fork under NethServer?

**Comment by DavidePrincipi** [comment]
Thank you @stephdl, I applied your patch to the upstream repo!

BTW: you should have write access to it

**Comment by stephdl** [comment]
close as per davidep comment

**Pull request closed without merging**
